### ISSUE TITLE
clip重叠时，仍可导出音频

### ISSUE THREAD

**Issue by wolfgitpr** [flutydeer/ds-editor-lite#11]
![image](https://github.com/user-attachments/assets/99dfc22f-8cd6-4f0d-ac98-34ba2290c380)
![image](https://github.com/user-attachments/assets/2a6e63f6-b20a-4b44-8bcf-d1c29dff9044)

**Comment by CrSjimo** [comment]
clip重叠的时候本来就可以正常播放，我觉得应该让笛鹿把播放的限制给取消了
