### ISSUE TITLE
片段提示错误后，已合成片段播放崩溃

### ISSUE THREAD

**Issue by wolfgitpr** [flutydeer/ds-editor-lite#16]
全部合成完之后，第一个分段随便改个+，一播放第二个分段崩溃
![3e98831518ee0fbe92140291101cfd06](https://github.com/user-attachments/assets/b06cdf54-c40e-4cc2-8e1d-5f3237054d12)
![image](https://github.com/user-attachments/assets/a0baf1bc-840b-4931-903d-60df6bf2e589)

**Comment by CrSjimo** [comment]
你要不自己先调一下，你这么放上来我也看不明白，`clip.content()`是`nullptr`吗？
