### ISSUE TITLE
音频clip长度与实际文件不符

### ISSUE THREAD

**Issue by wolfgitpr** [flutydeer/ds-editor-lite#6]
https://github.com/flutydeer/ds-editor-lite/issues/5

[241019-1230-bug.zip](https://github.com/user-attachments/files/17443344/241019-1230-bug.zip)

手动修改dspx中audio路径为zip中惊鹊.wav，打开au或任意daw占用此wav，播放到音频clip崩溃；如果文件未被占用，会触发另一个bug

打开au占用：
![058b23e191368a44bd72e38d4b8429ad](https://github.com/user-attachments/assets/cbd37c0a-1833-4304-baee-96d5d7d829a8)
![b49429275ed358ad6cc3e7615d3956ad](https://github.com/user-attachments/assets/a9a8f8a3-2fda-442d-b167-409d5aa7ebb5)

关闭au、音频未被占用：
![447e92b5742e7b2388a5a8bd1259bda8](https://github.com/user-attachments/assets/afcdf62f-2a94-49ab-a569-510d27630040)

**Comment by wolfgitpr** [comment]
未开au占用时（补）：
![image](https://github.com/user-attachments/assets/f3f2030b-db71-44d6-a4b3-367cc86c0cb5)
![image](https://github.com/user-attachments/assets/c651dd2a-737b-40fa-87e4-ecdbb27f0cc0)

**Comment by CrSjimo** [comment]
我确实没测试过音频文件占用或者不存在时候是怎么处理的，等我试试
